services:
  trackmoney_api:
    image: parimalmahindrakar/track_money_api:track-money-v4
    command: gunicorn -b 0.0.0.0:5010 src.main:app
    volumes:
      - .:/app
    ports:
      - 5010:5010
    env_file:
      - .env
    environment:
      - FLASK_APP=src/main.py
      - MONGO_DATABASE_URI=mongodb+srv://parimalm4653:ParimalTM18@trackmoneyapi.1jzih.mongodb.net/
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

  trackmoney_update_bank_and_expenses:
    image: parimalmahindrakar/track_money_api:track-money-v4
    command: celery -A src.main.celery_app worker -l info
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - FLASK_APP=src/main.py
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - MONGO_DATABASE_URI=mongodb+srv://parimalm4653:ParimalTM18@trackmoneyapi.1jzih.mongodb.net/

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
