services:
  trackmoney_api:
    image: parimalmahindrakar/track_money_api:latest
    command: gunicorn -w 1 --bind 0.0.0.0:4653 wsgi:app
    volumes:
      - .:/app
    ports:
      - 4653:4653
    env_file:
      - ./env/.env.prod

  trackmoney_update_bank_and_expenses:
    image: parimalmahindrakar/track_money_api:latest
    command: celery -A wsgi.celery_app worker -l info
    env_file:
      - ./env/.env.prod
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
