services:
  trackmoney_api:
    image: parimalmahindrakar/track_money_api:latest
    command: gunicorn -w 1 --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file:
      - ../env/.env.prod
    networks:
      - my_network

  celery_worker_with_beat:
    image: parimalmahindrakar/track_money_api:latest
    command: celery -A manage.celery worker --beat --loglevel=info
    env_file:
      - ../env/.env.prod
    networks:
      - my_network
    depends_on:
      - rabbitmq

  celery_worker_daily_expenses_emails:
    image: parimalmahindrakar/track_money_api:latest
    command: celery -A src.workers.celery_worker_send_daily_expenses_emails worker -l info -n send_daily_expenses_emails -c 1 -Ofair -Q daily_expenses_notifications_queue
    env_file:
      - ../env/.env.prod
    networks:
      - my_network
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network

  nginx:
    image: parimalmahindrakar/tracemymoney_nginx:latest
    container_name: tm_nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/ssl/certs/tm_keys:/etc/ssl/certs/tm_keys"
    depends_on:
      - trackmoney_api
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
