name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t parimalmahindrakar/track_money_api:latest .

      - name: Push Docker Image
        run: |
          docker push parimalmahindrakar/track_money_api:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Step 1: Remove the directory
            DIRECTORY="/home/ubuntu/TrackMoneyAPI"
            if [ -d "$DIRECTORY" ]; then
              echo "Removing directory: $DIRECTORY"
              sudo rm -rf "$DIRECTORY"
            else
              echo "Directory does not exist: $DIRECTORY"
            fi

            # Step 2: Stop all containers and remove Docker images
            echo "Stopping all containers and removing images"
            docker stop $(docker ps -aq) || true
            docker rm $(docker ps -aq) || true
            docker rmi $(docker images -q) || true

            # Step 3: Clone the repository and navigate into the directory
            REPO_URL="git@github.com:parimalmahindrakar/TrackMoneyAPI.git"
            git clone $REPO_URL
            cd "$DIRECTORY"

            # Step 4: Use docker-compose to bring up containers
            echo "Starting containers with docker-compose"
            docker-compose up -d
          EOF
