name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:8
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: jKFLXJCoGgsVCoiO
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables for testing
        run: |
          set -a
          source ./env/.test_env
          set +a

      - name: Wait for MongoDB to be ready
        run: |
          echo "Waiting for MongoDB to be ready..."
          while ! docker exec $(docker ps -qf "ancestor=mongo:8") mongo --username admin --password jKFLXJCoGgsVCoiO --authenticationDatabase admin --eval "db.runCommand({ ping: 1 })" > /dev/null 2>&1; do
            echo "MongoDB is not ready yet, waiting...";
            sleep 3;
          done
          echo "MongoDB is ready!"

      - name: Run pytest
        run: |
          pytest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t parimalmahindrakar/track_money_api:latest .

      - name: Push Docker Image
        run: |
          docker push parimalmahindrakar/track_money_api:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Step 1: Remove the directory
            DIRECTORY="/home/ubuntu/TrackMoneyAPI"
            if [ -d "$DIRECTORY" ]; then
              echo "Removing directory: $DIRECTORY"
              sudo rm -rf "$DIRECTORY"
            else
              echo "Directory does not exist: $DIRECTORY"
            fi

            # Step 2: Stop all containers and remove Docker images
            echo "Stopping all containers and removing images"
            docker stop $(docker ps -aq)
            docker rm $(docker ps -aq)
            docker rmi $(docker images -q)

            # Step 3: Clone the repository and navigate into the directory
            REPO_URL="git@github.com:parimalmahindrakar/TrackMoneyAPI.git"
            git clone $REPO_URL
            cd "$DIRECTORY"

            # Step 4: Use docker-compose to bring up containers
            echo "Starting containers with docker-compose"
            docker-compose -f docker-compose.yaml up -d
          EOF
