name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: '8'
          mongodb-root-username: admin
          mongodb-root-password: jKFLXJCoGgsVCoiO

      - name: Set environment variables for testing
        run: |
          set -a
          source ./env/.test_env
          set +a

      - name: Run pytest
        run: |
          pytest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Git version
        id: git-version
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          COMMIT=$(git rev-parse --short HEAD)
          VERSION="${BRANCH}_${COMMIT}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"

      - name: Build Docker Image
        run: |
          docker build -t parimalmahindrakar/track_money_api:${{ env.VERSION }} .

          # Tag it again with latest
          docker tag parimalmahindrakar/track_money_api:${{ env.VERSION }} parimalmahindrakar/track_money_api:latest

      - name: Push Docker Images
        run: |
          docker push parimalmahindrakar/track_money_api:${{ env.VERSION }}
          docker push parimalmahindrakar/track_money_api:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            DIRECTORY="/home/ubuntu/TrackMoneyAPI"
            if [ -d "$DIRECTORY" ]; then
              echo "Removing directory: $DIRECTORY"
              sudo rm -rf "$DIRECTORY"
            else
              echo "Directory does not exist: $DIRECTORY"
            fi

            echo "Stopping all containers and removing images"
            docker stop $(docker ps -aq)
            docker rm $(docker ps -aq)
            docker rmi $(docker images -q)

            REPO_URL="git@github.com:parimalmahindrakar/TrackMoneyAPI.git"
            git clone $REPO_URL
            cd "$DIRECTORY"

            echo "Starting containers with docker-compose"
            docker compose -f docker-compose.yaml up -d
          EOF
